package com.shoppix.product_reactive_service.enums;

public enum InventoryEnum {

    PRODUCT_INVENTORY_INIT_IN_PROGRESS,
    PRODUCT_INVENTORY_UPDATED,
    PRODUCT_INVENTORY_INIT_SUCCESS,
    PRODUCT_INVENTORY_INIT_FAILED,
    PRODUCT_INVENTORY_DELETED
}
