version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongodb:
    image: mongo6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  config-reactive-service:
    container_name: config-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/dev-kartik4/springboot-microservices-ecom/tree/main/config_service_reactive
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network


  customer-reactive-service:
    container_name: customer-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8110:8110"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8110/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network


  product-reactive-service:
    container_name: product-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8220:8220"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8220/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network

  inventory-reactive-service:
    container_name: inventory-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8330:8330"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8330/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network

  offers-reactive-service:
    container_name: offers-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8440:8440"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8440/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network


  cart-reactive-service:
    container_name: cart-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8550:8550"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8550/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network


  order-reactive-service:
    container_name: order-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8660:8660"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8660/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network


  checkout-reactive-service:
    container_name: checkout-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8770:8770"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8770/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network

  notification-reactive-service:
    container_name: notification-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8770:8770"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8880/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network


  merchant-reactive-service:
    container_name: merchant-reactive-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8990:8990"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config_service_reactive:8888
    depends_on:
      - config-reactive-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8990/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - springboot-ecom-network


networks:
  springboot-ecom-network:
    external: false
    name: springboot-ecom-network

