FROM openjdk:17
EXPOSE 8880
LABEL authors="kartikcodes.dev"
ADD target/springboot-notification-reactive-service-docker.jar springboot-notification-reactive-service-docker.jar
ENTRYPOINT ["java","-jar","springboot-notification-reactive-service-docker.jar"]
