server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dev-kartik4/springboot-microservices-ecom
          clone-on-start: true
          username:
          password:
        default-label: main

