FROM openjdk:17
EXPOSE 8660
LABEL authors="kartikcodes.dev"
ADD target/springboot-order-reactive-service-docker.jar springboot-order-reactive-service-docker.jar
ENTRYPOINT ["java","-jar","springboot-order-reactive-service-docker.jar"]
