server:
  port: 8888

spring:
  application:
    name: config-reactive-service
  main:
    web-application-type: reactive
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true
    config:
      uri: http://config-reactive-service:8888
      server:
        git:
          uri: https://github.com/dev-kartik4/springboot-microservices-ecom
          clone-on-start: true
        default-label: main

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-reactive-service:8761/eureka/
  instance:
    app-name: config-reactive-service
    hostname: config-reactive-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      config-reactive-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      config-reactive-service:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 10s

  ratelimiter:
    instances:
      config-reactive-service:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s