server:
  port: 8888

spring:
  application:
    name: config-reactive-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dev-kartik4/springboot-microservices-ecom
          clone-on-start: true
          username: dev-kartik4
          password: kPHONENUMBER@04
        default-label: main

