server:
  port: 8660

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myrogdb
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
#    instance-id: ${spring.application.name}:${random.uuid}
