server:
  port: 8660

spring:
  cloud:
    config:
      uri: http://localhost:8888
  data:
    mongodb:
      #      database: ORDERS
      #      host: orderservice
      #      port: 27017
      uri: mongodb+srv://dev:dev@cluster0.lyqgp.mongodb.net/myrogdb?retryWrites=true&w=majority
      database: myrogdb
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.uuid}
