FROM openjdk:17
EXPOSE 8110
ADD target/springboot-ecom-customer-service-reactive.jar springboot-ecom-customer-service-reactive.jar
ENTRYPOINT ["java","-jar","springboot-ecom-customer-service-reactive.jar"]