FROM openjdk:17
EXPOSE 8761
LABEL authors="kartikcodes.dev"
ADD target/springboot-ecom-eurekaservice.jar springboot-ecom-eurekaservice.jar
ENTRYPOINT ["java","-jar","springboot-ecom-eurekaservice.jar"]