server:
  port: 8880

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: notification-reactive-service
  main:
    web-application-type: reactive
    allow-circular-references: true
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      customer-notification-topic: customer-notification-topic
      order-notification-topic: order-notification-topic
      cart-notification-topic: cart-notification-topic
      payment-notification-topic: payment-notification-topic
      offers-notification-topic: offers-notification-topic
      shipping-notification-topic: shipping-notification-topic
    dead-letter:
      customer-notification-dlt: customer-notification-dlt
      order-notification-dlt: order-notification-dlt
      cart-notification-dlt: cart-notification-dlt
      payment-notification-dlt: payment-notification-dlt
      offers-notification-dlt: offers-notification-dlt
      shipping-notification-dlt: shipping-notification-dlt
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    consumer:
      group-id: notification-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: kartiktelikicherla@gmail.com
    password: nhjm nvjz mnwl fdhu
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: notification-reactive-service
    hostname: localhost
    prefer-ip-address: true