FROM openjdk:17
EXPOSE 8990
LABEL authors="kartikcodes.dev"
ADD target/springboot-merchant-reactive-service-docker.jar springboot-merchant-reactive-service-docker.jar
ENTRYPOINT ["java","-jar","springboot-merchant-reactive-service-docker.jar"]
