FROM openjdk:17
EXPOSE 8220
LABEL authors="kartikcodes.dev"
ADD target/springboot-product-reactive-service-docker.jar springboot-product-reactive-service-docker.jar
ENTRYPOINT ["java","-jar","springboot-product-reactive-service-docker.jar"]
