server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  server:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: eureka-reactive-service