server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-service-url-poll-interval-seconds: 30
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://eureka-reactive-service:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: eureka-reactive-service
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    eureka:
      enabled: true
