server:
  port: 8761

spring:
  application:
    name: eureka-reactive-service
  main:
    web-application-type: reactive
    allow-circular-references: true
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-service-url-poll-interval-seconds: 30
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://eureka-reactive-service:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    app-name: eureka-reactive-service
    hostname: eureka-reactive-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  health:
    eureka:
      enabled: true
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
