FROM openjdk:17
EXPOSE 8220
LABEL authors="kartikcodes.dev"
ADD target/springboot-offers-reactive-service-docker.jar springboot-offers-reactive-service-docker.jar
ENTRYPOINT ["java","-jar","springboot-offers-reactive-service-docker.jar"]
